task 6 complete
FameTii/BE-boardgames pull request #4
Opened 2023-02-21 16:17 UTC by FameTii

2023-02-21 16:55 UTC, Augs0 requested changes
Wonderful job, Fame, really well done. Just a few things to add in the tests!

2023-02-21 16:55 UTC, Augs0 commented on API/app.test.js
> +                expect(body.comments).toEqual(
We should also check the length of the array here

2023-02-21 16:55 UTC, Augs0 commented on API/app.test.js
> +    })
We should have another 200 test here that returns an empty array if the article exists but has no comments

2023-02-21 16:55 UTC, Augs0 commented on API/app.test.js
> +    it("should respond with 404 and comment not found", () => {
This should check if the article exists rather than the comments

2023-02-21 16:55 UTC, Augs0 commented on API/models.js
> +// SELECT * FROM comments WHERE review_id = 3 ORDER BY created_at DESC;
Don't forget to remove console logs!

2023-02-22 09:35 UTC, pippaamy approved these changes
Nice go ahead and merge!

2023-02-22 09:36 UTC, merged